# Generated by Django 4.2.6 on 2024-08-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'db_table': 'ins_bloco',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'ins_cidade',
            },
        ),
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('tensao', models.FloatField(default=0.0)),
                ('corrente', models.FloatField(default=0.0)),
                ('potencia', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Dado',
                'verbose_name_plural': 'Dados',
                'db_table': 'ins_dado',
            },
        ),
        migrations.CreateModel(
            name='Instituicao_Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_simplificado', models.CharField(blank=True, max_length=250)),
                ('nome_completo', models.CharField(max_length=250)),
                ('sigla', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo da Instituição',
                'verbose_name_plural': 'Tipos das Instituições',
                'db_table': 'ins_instituicao_tipo',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'db_table': 'ins_localizacao',
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'db_table': 'ins_regiao',
            },
        ),
        migrations.CreateModel(
            name='Quadro_Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.bloco')),
            ],
            options={
                'verbose_name': 'Quadro de Energia',
                'verbose_name_plural': 'Quadros de Energia',
                'db_table': 'ins_quadro_energia',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('sigla', models.CharField(max_length=2)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.regiao')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'ins_estado',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_teste', models.CharField(max_length=250)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'ins_endereco',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.dado')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.localizacao')),
                ('quadro_energia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.quadro_energia')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'ins_dispositivo',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.estado'),
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250)),
                ('sigla', models.CharField(blank=True, max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.endereco')),
                ('instituicao_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.instituicao_tipo')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
                'db_table': 'ins_campus',
            },
        ),
        migrations.AddField(
            model_name='bloco',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.campus'),
        ),
    ]
