# Generated by Django 4.2.6 on 2024-08-08 20:31

from django.db import migrations

# Função para inserir os dados das regiões e estados
def insere_dados(apps, schema_editor):
    Regiao = apps.get_model('instituicoes', 'Regiao')
    Estado = apps.get_model('instituicoes', 'Estado')
    Cidade = apps.get_model('instituicoes', 'Cidade')
    Tipo = apps.get_model('instituicoes', 'Instituicao_Tipo')
    Endereco = apps.get_model('instituicoes', 'Endereco')
    Campus = apps.get_model('instituicoes', 'Campus')
    Bloco = apps.get_model('instituicoes', 'Bloco')
    Quadro = apps.get_model('instituicoes', 'Quadro_Energia')
    Dado = apps.get_model('instituicoes', 'Dado')
    Localizacao = apps.get_model('instituicoes', 'Localizacao')
    Dispositivo = apps.get_model('instituicoes', 'Dispositivo')

    # Dados das regiões
    regioes_data = [
        {"id":1,"nome": "Centro-oeste"},
        {"id":2,"nome": "Nordeste"},
        {"id":3,"nome": "Norte"},
        {"id":4,"nome": "Sudeste"},
        {"id":5,"nome": "Sul"},
    ]
    for regiao_data in regioes_data:
        Regiao.objects.create(**regiao_data)

    # Dados dos estados
    estados_data = [
        {"id": 1, "nome": "Acre", "sigla": "AC", "regiao": Regiao.objects.get(id=3)},
        {"id": 2,  "nome": "Alagoas", "sigla": "AL", "regiao": Regiao.objects.get(id=2)},
        {"id": 3,  "nome": "Amapá", "sigla": "AP", "regiao": Regiao.objects.get(id=3)},
        {"id": 4,  "nome": "Amazonas", "sigla": "AM", "regiao": Regiao.objects.get(id=3)},
        {"id": 5,  "nome": "Bahia", "sigla": "BA", "regiao": Regiao.objects.get(id=2)},
        {"id": 6,  "nome": "Ceará", "sigla": "CE", "regiao": Regiao.objects.get(id=2)},
        {"id": 7,  "nome": "Distrito Federal", "sigla": "DF", "regiao": Regiao.objects.get(id=1)},
        {"id": 8,  "nome": "Espírito Santo", "sigla": "ES", "regiao": Regiao.objects.get(id=4)},
        {"id": 9,  "nome": "Goiás", "sigla": "GO", "regiao": Regiao.objects.get(id=1)},
        {"id": 10, "nome": "Maranhão", "sigla": "MA", "regiao": Regiao.objects.get(id=2)},
        {"id": 11, "nome": "Mato Grosso", "sigla": "MT", "regiao": Regiao.objects.get(id=1)},
        {"id": 12, "nome": "Mato Grosso do Sul", "sigla": "MS", "regiao": Regiao.objects.get(id=1)},
        {"id": 13, "nome": "Minas Gerais", "sigla": "MG", "regiao": Regiao.objects.get(id=4)},
        {"id": 14, "nome": "Pará", "sigla": "PA", "regiao": Regiao.objects.get(id=3)},
        {"id": 15, "nome": "Paraíba", "sigla": "PB", "regiao": Regiao.objects.get(id=2)},
        {"id": 16, "nome": "Paraná", "sigla": "PR", "regiao": Regiao.objects.get(id=5)},
        {"id": 17, "nome": "Pernambuco", "sigla": "PE", "regiao": Regiao.objects.get(id=2)},
        {"id": 18, "nome": "Piauí", "sigla": "PI", "regiao": Regiao.objects.get(id=2)},
        {"id": 19, "nome": "Rio de Janeiro", "sigla": "RJ", "regiao": Regiao.objects.get(id=4)},
        {"id": 20, "nome": "Rio Grande do Norte", "sigla": "RN", "regiao": Regiao.objects.get(id=2)},
        {"id": 21, "nome": "Rio Grande do Sul", "sigla": "RS", "regiao": Regiao.objects.get(id=5)},
        {"id": 22, "nome": "Rondônia", "sigla": "RO", "regiao": Regiao.objects.get(id=3)},
        {"id": 23, "nome": "Roraima", "sigla": "RR", "regiao": Regiao.objects.get(id=3)},
        {"id": 24, "nome": "Santa Catarina", "sigla": "SC", "regiao": Regiao.objects.get(id=5)},
        {"id": 25, "nome": "São Paulo", "sigla": "SP", "regiao": Regiao.objects.get(id=4)},
        {"id": 26, "nome": "Sergipe", "sigla": "SE", "regiao": Regiao.objects.get(id=2)},
        {"id": 27, "nome": "Tocantins", "sigla": "TO", "regiao": Regiao.objects.get(id=3)},
    ]
    for estado_data in estados_data:
        Estado.objects.create(**estado_data)
        
    cidade_data = [
        {"id": 1, "nome": "Araguaína ", "estado": Estado.objects.get(id=27)},
        {"id": 2, "nome": "Araguatins", "estado": Estado.objects.get(id=27)},
        {"id": 3, "nome": "Colinas do Tocantins", "estado": Estado.objects.get(id=27)},
        {"id": 4, "nome": "Dianópolis", "estado": Estado.objects.get(id=27)},
        {"id": 5, "nome": "Formoso do Araguaia", "estado": Estado.objects.get(id=27)},
        {"id": 6, "nome": "Gurupi", "estado": Estado.objects.get(id=27)},
        {"id": 7, "nome": "Lagoa da Confusão", "estado": Estado.objects.get(id=27)},
        {"id": 8, "nome": "Palmas", "estado": Estado.objects.get(id=27)},
        {"id": 9, "nome": "Paraíso do Tocantins", "estado": Estado.objects.get(id=27)},
        {"id": 10, "nome": "Pedro Afonso", "estado": Estado.objects.get(id=27)},
        {"id": 11, "nome": "Porto Nacional", "estado": Estado.objects.get(id=27)},
    ]  
    for cidade_data in cidade_data:
        Cidade.objects.create(**cidade_data)

    tipos_instituicao_data = [
        {"id": 1, "nome_simplificado": "Instituto Federal", "nome_completo": "Institutos Federais de Educação, Ciência e Tecnologia", "sigla": "IF"},
        {"id": 2, "nome_simplificado": "Universidade Federal", "nome_completo": "Universidade Tecnológica Federal do Paraná", "sigla": "UF"},
        {"id": 3, "nome_completo": "Centros Federais de Educação Tecnológica", "sigla": "Cefet"},
        {"id": 4, "nome_completo": "Escolas técnicas vinculadas"},
        {"id": 5, "nome_simplificado": "Pedro II", "nome_completo": "Colégio Pedro II", "sigla": "CPII"},
        {"id": 6, "nome_completo": "Reitoria"},
    ]
    for tipos_instituicao_data in tipos_instituicao_data:
        Tipo.objects.create(**tipos_instituicao_data)

    endereco_data = [
        {"id": 1, "endereco_teste": "Av. Amazonas, esquina com a Av. Paraguai, Quadra 56, Lote 01, Setor Cimba", "cidade": Cidade.objects.get(id=1)},
        {"id": 2, "endereco_teste": "Povoado Santa Teresa - Km 05, Zona Rural", "cidade": Cidade.objects.get(id=2)},
        {"id": 3, "endereco_teste": "Avenida Bernardo Sayão, Lote 29B, Setor Santa Maria, Chácara Raio de Sol", "cidade": Cidade.objects.get(id=3)},
        {"id": 4, "endereco_teste": "Rodovia TO 040 - Km 349 Loteamento Rio Palmeira - Lote 1", "cidade": Cidade.objects.get(id=4)},
        {"id": 5, "endereco_teste": "Rua do Açude, s/n, Centro, próximo ao Lago Municipal", "cidade": Cidade.objects.get(id=5)},
        {"id": 6, "endereco_teste": "Alameda Madrid, 545 - Jardim Sevilha", "cidade": Cidade.objects.get(id=6)},
        {"id": 7, "endereco_teste": "Rua 02, Quadra 5A, Lote 01, Setor Lagoa da Ilha", "cidade": Cidade.objects.get(id=7)},
        {"id": 8, "endereco_teste": "AE 310 Sul, Avenida LO 05, s/n, Plano Diretor Sul", "cidade": Cidade.objects.get(id=8)},
        {"id": 9, "endereco_teste": "Distrito Agroindustrial, BR 153, KM 480", "cidade": Cidade.objects.get(id=9)},
        {"id": 10, "endereco_teste": "Rua Ceará, n.º 1441, Setor Zacarias Campelo", "cidade": Cidade.objects.get(id=10)},
        {"id": 11, "endereco_teste": "Avenida Tocantins, A.I. - Loteamento Mãe Dedé,  Jardim América", "cidade": Cidade.objects.get(id=11)},
        {"id": 12, "endereco_teste": "Avenida Joaquim Teotônio Segurado, Quadra 202 sul, ACSU-SE 20, Conjunto 1, Lote 8", "cidade": Cidade.objects.get(id=8)},
    ]
    for endereco_data in endereco_data:
        Endereco.objects.create(**endereco_data)

    campus_data = [
        {"id": 1, "nome": "CAMPUS ARAGUAÍNA", "sigla": "IF", "endereco": Endereco.objects.get(id=1), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 2, "nome": "CAMPUS ARAGUATINS", "sigla": "IF", "endereco": Endereco.objects.get(id=2), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 3, "nome": "CAMPUS COLINAS DO TOCANTINS", "sigla": "IF", "endereco": Endereco.objects.get(id=3), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 4, "nome": "CAMPUS DIANÓPOLIS", "sigla": "IF", "endereco": Endereco.objects.get(id=4), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 5, "nome": "CAMPUS AVANÇADO FORMOSO DO ARAGUAIA", "endereco": Endereco.objects.get(id=5), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 6, "nome": "CAMPUS GURUPI", "sigla": "IF", "endereco": Endereco.objects.get(id=6), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 7, "nome": "CAMPUS AVANÇADO LAGOA DA CONFUSÃO", "endereco": Endereco.objects.get(id=7), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 8, "nome": "CAMPUS PALMAS", "sigla": "IF", "endereco": Endereco.objects.get(id=8), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 9, "nome": "CAMPUS PARAÍSO DO TOCANTINS", "sigla": "IF", "endereco": Endereco.objects.get(id=9), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 10, "nome": "CAMPUS AVANÇADO PEDRO AFONSO", "endereco": Endereco.objects.get(id=10), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 11, "nome": "CAMPUS PORTO NACIONAL", "sigla": "IF", "endereco": Endereco.objects.get(id=10), "instituicao_tipo": Tipo.objects.get(id=1)},
        {"id": 12, "nome": "REITORIA IFTO", "sigla": "IF", "endereco": Endereco.objects.get(id=11), "instituicao_tipo": Tipo.objects.get(id=6)},
    ]
    for campus_data in campus_data:
        Campus.objects.create(**campus_data)

    bloco_data = [
        {"id": 1, "nome": "bloco1", "campus": Campus.objects.get(id=1)},
        {"id": 2, "nome": "bloco2", "campus": Campus.objects.get(id=1)},
        {"id": 3, "nome": "bloco3", "campus": Campus.objects.get(id=1)},
        {"id": 4, "nome": "bloco4", "campus": Campus.objects.get(id=2)},
        {"id": 5, "nome": "bloco5", "campus": Campus.objects.get(id=2)},
        {"id": 6, "nome": "bloco6", "campus": Campus.objects.get(id=2)},
        {"id": 7, "nome": "bloco7", "campus": Campus.objects.get(id=3)},
        {"id": 8, "nome": "bloco8", "campus": Campus.objects.get(id=4)},
        {"id": 9, "nome": "bloco9", "campus": Campus.objects.get(id=4)},
        {"id": 10, "nome": "bloco10", "campus": Campus.objects.get(id=5)},
        {"id": 11, "nome": "bloco11", "campus": Campus.objects.get(id=6)},
        {"id": 12, "nome": "bloco12", "campus": Campus.objects.get(id=7)},
    ]
    for bloco_data in bloco_data:
        Bloco.objects.create(**bloco_data)

    quadro_data = [
        {"id": 1, "bloco": Bloco(id=1)},
        {"id": 2, "bloco": Bloco(id=2)},
        {"id": 3, "bloco": Bloco(id=3)},
        {"id": 4, "bloco": Bloco(id=4)},
        {"id": 5, "bloco": Bloco(id=5)},
        {"id": 6, "bloco": Bloco(id=6)},
        {"id": 7, "bloco": Bloco(id=7)},
        {"id": 8, "bloco": Bloco(id=8)},
        {"id": 9, "bloco": Bloco(id=9)},
        {"id": 10, "bloco": Bloco(id=10)},
        {"id": 11, "bloco": Bloco(id=11)},
        {"id": 12, "bloco": Bloco(id=12)},
    ]
    for quadro_data in quadro_data:
        Quadro.objects.create(**quadro_data)

    dado_data = [
        {"id": 1, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 2, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 3, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 4, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 5, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 6, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 7, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 8, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 9, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 10, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 11, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
        {"id": 12, "status": False, "tensao": 0.00, "corrente": 0.00, "potencia": 0.00},
    ]
    for dado_data in dado_data:
        Dado.objects.create(**dado_data)

    localizacao_data =[
        {"id": 1, "latitude": -56.0082, "longitude": 136.5012},
        {"id": 2, "latitude": -4.5237, "longitude": -32.6564},
        {"id": 3, "latitude": 27.7659, "longitude": -74.4984},
        {"id": 4, "latitude": -81.8279, "longitude": -141.1752},
        {"id": 5, "latitude": 45.8246, "longitude": 67.1806},
        {"id": 6, "latitude": 29.3474, "longitude": -41.6691},
        {"id": 7, "latitude": 8.2868, "longitude": 118.7946},
        {"id": 8, "latitude": 6.2249, "longitude": -61.9742},
        {"id": 9, "latitude": 39.9209, "longitude": -179.0287},
        {"id": 10, "latitude": 38.4163, "longitude": -150.9048},
        {"id": 11, "latitude": -76.4731, "longitude": -133.0428},
        {"id": 12, "latitude": -3.0881, "longitude": -142.9083},
        {"id": 13, "latitude": 48.2051, "longitude": -19.1582},
        {"id": 14, "latitude": -57.2505, "longitude": -43.5062},
        {"id": 15, "latitude": -71.6269, "longitude": -121.7497},
    ]
    for localizacao_data in localizacao_data:
        Localizacao.objects.create(**localizacao_data)
        
    dispositivo_data =[
        {"id": 1, "quadro_energia": Quadro(id=1), "dado": Dado.objects.get(id=1), "localizacao": Localizacao.objects.get(id=1)},
        {"id": 2, "quadro_energia": Quadro(id=1), "dado": Dado.objects.get(id=2), "localizacao": Localizacao.objects.get(id=2)},
        {"id": 3, "quadro_energia": Quadro(id=1), "dado": Dado.objects.get(id=3), "localizacao": Localizacao.objects.get(id=3)},
        {"id": 4, "quadro_energia": Quadro(id=2), "dado": Dado.objects.get(id=4), "localizacao": Localizacao.objects.get(id=4)},
        {"id": 5, "quadro_energia": Quadro(id=3), "dado": Dado.objects.get(id=5), "localizacao": Localizacao.objects.get(id=5)},
        {"id": 6, "quadro_energia": Quadro(id=4), "dado": Dado.objects.get(id=6), "localizacao": Localizacao.objects.get(id=6)},
        {"id": 7, "quadro_energia": Quadro(id=5), "dado": Dado.objects.get(id=7), "localizacao": Localizacao.objects.get(id=7)},
        {"id": 8, "quadro_energia": Quadro(id=6), "dado": Dado.objects.get(id=8), "localizacao": Localizacao.objects.get(id=8)},
        {"id": 9, "quadro_energia": Quadro(id=7), "dado": Dado.objects.get(id=9), "localizacao": Localizacao.objects.get(id=9)},
        {"id": 10, "quadro_energia": Quadro(id=8), "dado": Dado.objects.get(id=9), "localizacao": Localizacao.objects.get(id=10)},
        {"id": 11, "quadro_energia": Quadro(id=8), "dado": Dado.objects.get(id=9), "localizacao": Localizacao.objects.get(id=11)},
        {"id": 12, "quadro_energia": Quadro(id=9), "dado": Dado.objects.get(id=10), "localizacao": Localizacao.objects.get(id=12)},
        {"id": 13, "quadro_energia": Quadro(id=9), "dado": Dado.objects.get(id=10), "localizacao": Localizacao.objects.get(id=13)},
        {"id": 14, "quadro_energia": Quadro(id=10), "dado": Dado.objects.get(id=11), "localizacao": Localizacao.objects.get(id=14)},
        {"id": 15, "quadro_energia": Quadro(id=11), "dado": Dado.objects.get(id=12), "localizacao": Localizacao.objects.get(id=15)},
    ]
    for dispositivo_data in dispositivo_data:
        Dispositivo.objects.create(**dispositivo_data)

class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insere_dados)
    ]
